title: Odissei Code Library
email: evokeapps@yahoo.com
baseurl: "/odissei-code-lib" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed
# CSV reading
csv_reader:
  converters:
    - numeric
    - datetime
  headers: true
  encoding: utf-8
